[package]
name = "oblivious_state_machine"
version = "0.3.0"
edition = "2021"
authors = ["victor.ermolaev@ing.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
pretty_env_logger = "0.4.0"
log = "0.4.14"
downcast-rs = "1.2.0"
thiserror = "1.0.24"

[dev-dependencies]
anyhow = "1.0.40"
